# Generated by Django 4.2.5 on 2023-11-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0002_project_breadth_project_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contractor_name', models.CharField(max_length=500)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attandance.project')),
            ],
        ),
        migrations.AlterField(
            model_name='officelogin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteengineer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaborTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labor_type', models.CharField(max_length=500)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attandance.contractor')),
            ],
        ),
    ]
