# Generated by Django 4.2.5 on 2023-11-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0003_contractor_alter_officelogin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('number_of_workers', models.PositiveIntegerField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.contractor')),
                ('labor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.labortypes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.project')),
            ],
        ),
    ]
