# Generated by Django 4.2.5 on 2023-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0005_labortypes_overtime_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
