# Generated by Django 4.2.5 on 2023-11-05 05:44

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0006_attendancerecord_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Breadth',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Area),
        ),
        migrations.AlterField(
            model_name='project',
            name='Length',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Area),
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('number_of_workers', models.PositiveIntegerField()),
                ('number_of_hours', models.PositiveIntegerField()),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.contractor')),
                ('labor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.labortypes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.project')),
            ],
        ),
    ]
