# Generated by Django 4.2.5 on 2023-11-06 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0008_materialcategory_alter_attendancerecord_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indent',
            name='indent_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
