# Generated by Django 4.2.5 on 2023-11-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0009_indent_date_indent_indent_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='Quantity_Recieved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indent',
            name='Quantity_order_status',
            field=models.BooleanField(default=False),
        ),
    ]
