# Generated by Django 4.2.5 on 2023-11-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0010_alter_indent_quantity_recieved_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_engineers',
            field=models.ManyToManyField(related_name='projects', to='attandance.siteengineer'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='indent_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
